=== JoaoGRRodrigues/rodd/etc/data/rodd-data/xml/tbl-Product_service_link.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="tbl-Product_service_link" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="tbl-Product_service_link">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="serviceID" index-key="serviceID " primary="no" unique="no" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="1"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAChFdzfxa1tSJ7lufX6rOHDAAAAAIvWnwm2r+NAAAAAAAAAAAB0AGIA
bAAtAFAAcgBvAGQAdQBjAHQAXwBzAGUAcgB2AGkAYwBlAF8AbABpAG4AawAAAAAA
AADGkSrbkpC4RJQRvX2Eo4r9AAAAADUreRC2r+NAAAOWAPhgEwB0AGIAbABfAFAA
cgBvAGQAdQBjAHQAcwAAAAAAAAB+YRwdFxkoSKY3h3lbf93HBwAAAMaRKtuSkLhE
lBG9fYSjiv1SAE8ARABEAEkARAAAAAAAAAB5oAcmaUVjSJ4qTX3lEm/NBwAAAMaR
KtuSkLhElBG9fYSjiv10AGkAdABsAGUAAAAAAAAAUsT8C1V000yjfoqC+NTr+QcA
AADGkSrbkpC4RJQRvX2Eo4r9YQBjAHIAAAAAAAAARIP0H7liUkuCimjEEnBmYwcA
AAChFdzfxa1tSJ7lufX6rOHDUgBPAEQARABJAEQAAAAAAAAAqwFO8j0BZk6n/tKl
XARaiAAAAADJIMaFtq3jQAADlgD4YBMAdABiAGwAXwBzAGUAcgB2AGkAYwBlAAAA
AAAAAJbVlJ2X0nNCg0vxHwBwRbgHAAAAqwFO8j0BZk6n/tKlXARaiHMAZQByAHYA
aQBjAGUASQBEAAAAAAAAAG3cd7W/bEpOn22XqAomTvEHAAAAqwFO8j0BZk6n/tKl
XARaiHMAZQByAHYAaQBjAGUAXwBkAGkAcgBlAGMAdABvAHIAeQAAAAAAAAAArCK5
TvNSR7qJgtmdL1dDBwAAAKEV3N/FrW1InuW59fqs4cNzAGUAcgB2AGkAYwBlAEkA
RAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAQAAAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="oRXc38WtbUie5bn1+qzhww==
"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="OrderBy" type="12" value="[Lookup_RODDID].[title]"/>
<od:tableProperty name="Filter" type="12" value="([Lookup_RODDID].[title] Like &quot;*jason-1*&quot;)"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="RODDID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="7680"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="110"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [tbl_Products].RODDID, [tbl_Products].title, [tbl_Products].acr FROM tbl_Products; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="6"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;3969;1701;0;0;3969"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="GUID" type="9" value="RIP0H7liUkuCimjEEnBmYw==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="serviceID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="4545"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="110"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="GUID" type="9" value="AKwiuU7zUke6iYLZnS9XQw==
"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT tbl_service.serviceID, tbl_service.service_directory FROM tbl_service; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1134"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== JoaoGRRodrigues/rodd/etc/data/rodd-data/tbl-Product_service_link.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="tbl-Product_service_link.xsd" generated="2010-06-25T11:54:58">
<tbl-Product_service_link>
<RODDID>5</RODDID>
<serviceID>41</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>6</RODDID>
<serviceID>61</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>8</RODDID>
<serviceID>43</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>9</RODDID>
<serviceID>43</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>11</RODDID>
<serviceID>33</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>12</RODDID>
<serviceID>33</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>13</RODDID>
<serviceID>44</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>14</RODDID>
<serviceID>44</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>15</RODDID>
<serviceID>816</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>16</RODDID>
<serviceID>816</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>17</RODDID>
<serviceID>45</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>18</RODDID>
<serviceID>62</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>19</RODDID>
<serviceID>32</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>22</RODDID>
<serviceID>47</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>23</RODDID>
<serviceID>63</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>24</RODDID>
<serviceID>35</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>28</RODDID>
<serviceID>137</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>29</RODDID>
<serviceID>137</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>31</RODDID>
<serviceID>825</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>32</RODDID>
<serviceID>137</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>37</RODDID>
<serviceID>816</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>40</RODDID>
<serviceID>816</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>41</RODDID>
<serviceID>816</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>42</RODDID>
<serviceID>816</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>43</RODDID>
<serviceID>141</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>45</RODDID>
<serviceID>827</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>46</RODDID>
<serviceID>825</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>47</RODDID>
<serviceID>71</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>58</RODDID>
<serviceID>137</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>59</RODDID>
<serviceID>138</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>65</RODDID>
<serviceID>141</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>66</RODDID>
<serviceID>141</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>67</RODDID>
<serviceID>71</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>68</RODDID>
<serviceID>137</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>73</RODDID>
<serviceID>141</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>84</RODDID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>85</RODDID>
<serviceID>132</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>87</RODDID>
<serviceID>141</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>88</RODDID>
<serviceID>804</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>89</RODDID>
<serviceID>795</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>90</RODDID>
<serviceID>825</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>103</RODDID>
<serviceID>36</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>104</RODDID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>109</RODDID>
<serviceID>795</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>115</RODDID>
<serviceID>17</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>116</RODDID>
<serviceID>17</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>119</RODDID>
<serviceID>804</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>121</RODDID>
<serviceID>17</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>122</RODDID>
<serviceID>804</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>124</RODDID>
<serviceID>825</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>125</RODDID>
<serviceID>799</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>127</RODDID>
<serviceID>134</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>128</RODDID>
<serviceID>135</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>135</RODDID>
<serviceID>134</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>136</RODDID>
<serviceID>135</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>139</RODDID>
<serviceID>49</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>141</RODDID>
<serviceID>51</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>150</RODDID>
<serviceID>53</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>151</RODDID>
<serviceID>66</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>152</RODDID>
<serviceID>816</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>164</RODDID>
<serviceID>71</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>166</RODDID>
<serviceID>55</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>167</RODDID>
<serviceID>57</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>168</RODDID>
<serviceID>57</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>169</RODDID>
<serviceID>56</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>171</RODDID>
<serviceID>57</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>172</RODDID>
<serviceID>57</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>174</RODDID>
<serviceID>93</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>175</RODDID>
<serviceID>92</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>180</RODDID>
<serviceID>92</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>181</RODDID>
<serviceID>92</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>182</RODDID>
<serviceID>92</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>184</RODDID>
<serviceID>804</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>187</RODDID>
<serviceID>825</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>188</RODDID>
<serviceID>804</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>189</RODDID>
<serviceID>17</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>191</RODDID>
<serviceID>16</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>193</RODDID>
<serviceID>59</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>194</RODDID>
<serviceID>67</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>195</RODDID>
<serviceID>72</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>196</RODDID>
<serviceID>85</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>197</RODDID>
<serviceID>156</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>198</RODDID>
<serviceID>107</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>200</RODDID>
<serviceID>134</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>201</RODDID>
<serviceID>135</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>202</RODDID>
<serviceID>70</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>203</RODDID>
<serviceID>16</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>204</RODDID>
<serviceID>816</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>205</RODDID>
<serviceID>816</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>206</RODDID>
<serviceID>105</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>207</RODDID>
<serviceID>100</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>208</RODDID>
<serviceID>106</serviceID>
</tbl-Product_service_link>
<tbl-Product_service_link>
<RODDID>211</RODDID>
