=== JoaoGRRodrigues/rodd/etc/data/rodd-data/xml/tbl_dissemination.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="tbl_dissemination" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="tbl_dissemination">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="ID" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAAZl7v+mUC9RqavR8kwj7WKAAAAAO13dg5zqeNAAAAAAAAAAAB0AGIA
bABfAGQAaQBzAHMAZQBtAGkAbgBhAHQAaQBvAG4AAAAAAAAA2odFKJmEJkG9Sy80
hdtRrAcAAAAZl7v+mUC9RqavR8kwj7WKSQBEAAAAAAAAAEfZOwKFPDdMsKufmEnS
HOIHAAAAGZe7/plAvUamr0fJMI+1ikYAaQBlAGwAZAAxAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAMAAAABAAAAAAAAAAAAAAAAAAAAAAA
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="GZe7/plAvUamr0fJMI+1ig==
"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Field1" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2820"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== JoaoGRRodrigues/rodd/etc/data/rodd-data/xml/tbl_dissemination.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="tbl_dissemination.xsd" generated="2010-06-25T11:54:34">
<tbl_dissemination>
<ID>1</ID>
<Field1>Archive </Field1>
</tbl_dissemination>
<tbl_dissemination>
<ID>2</ID>
<Field1>AVISO  </Field1>
</tbl_dissemination>
<tbl_dissemination>
<ID>3</ID>
<Field1>CLASS </Field1>
</tbl_dissemination>
<tbl_dissemination>
<ID>4</ID>
<Field1>Direct </Field1>
</tbl_dissemination>
<tbl_dissemination>
<ID>5</ID>
<Field1>EUMETCast</Field1>
</tbl_dissemination>
<tbl_dissemination>
<ID>6</ID>
<Field1>EUMETCast-Africa </Field1>
</tbl_dissemination>
<tbl_dissemination>
<ID>7</ID>
<Field1>EUMETCast-Americas </Field1>
</tbl_dissemination>
<tbl_dissemination>
<ID>8</ID>
<Field1>EUMETCast-Europe </Field1>
</tbl_dissemination>
<tbl_dissemination>
<ID>9</ID>
<Field1>EUMETSAT Data Centre</Field1>
</tbl_dissemination>
<tbl_dissemination>
<ID>10</ID>
<Field1>EUMETSATWebsite </Field1>
</tbl_dissemination>
<tbl_dissemination>
<ID>11</ID>
<Field1>FENGYUNCast</Field1>
</tbl_dissemination>
<tbl_dissemination>
<ID>12</ID>
<Field1>FTP </Field1>
</tbl_dissemination>
<tbl_dissemination>
<ID>13</ID>
<Field1>GEONETCast-Americas </Field1>
</tbl_dissemination>
<tbl_dissemination>
<ID>14</ID>
<Field1>GTS</Field1>
</tbl_dissemination>
<tbl_dissemination>
<ID>15</ID>
<Field1>Internet </Field1>
</tbl_dissemination>
<tbl_dissemination>
<ID>16</ID>
<Field1>NOAA</Field1>
</tbl_dissemination>
<tbl_dissemination>
<ID>17</ID>
<Field1>SAF Archive</Field1>
</tbl_dissemination>
<tbl_dissemination>
<ID>18</ID>
<Field1>SAF Software </Field1>
</tbl_dissemination>
</dataroot>
