=== JoaoGRRodrigues/rodd/etc/data/rodd-data/xml/tbl_families.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="tbl_families" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="tbl_families">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="familyID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="1"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAACaCx/FiT/iTZzfktUvTAtEAAAAALPf2ZFTqeNAbGUAAAAAAAB0AGIA
bABfAGYAYQBtAGkAbABpAGUAcwAAAAAAAACpzw32EhUyR7bL2l0+J8nrBwAAAJoL
H8WJP+JNnN+S1S9MC0RmAGEAbQBpAGwAeQBJAEQAAAAAAAAA+Jtp8Mys20SPzlb0
+Ea/+gcAAACaCx/FiT/iTZzfktUvTAtEZABpAHMAcABsAGEAeQBfAG4AYQBtAGUA
AAAAAAAAiSZkL9Z4vUqNeP7OudTA1wcAAACaCx/FiT/iTZzfktUvTAtEZgBhAG0A
aQBsAHkAAAAAAAAA+4fi9pkJtUKW+dUh+dopKAAAAACRXd8D1q3jQP////8iApF8
dABiAGwAXwBzAGUAcgB2AGkAYwBlAF8AZgBhAG0AaQBsAHkAXwBsAGkAbgBrAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAABAAAAAAAAAAAAAAAAAAAAAAA
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="mgsfxYk/4k2c35LVL0wLRA==
"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="OrderBy" type="12" value="[tbl_families].[familyID], [tbl_families].[display_name], [tbl_families].[family]"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="familyID" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="General Number"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="GUID" type="9" value="qc8N9hIVMke2y9pdPifJ6w==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="family" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="ColumnWidth" type="3" value="4455"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="GUID" type="9" value="iSZkL9Z4vUqNeP7OudTA1w==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="display_name" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="ColumnWidth" type="3" value="5385"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="GUID" type="9" value="+Jtp8Mys20SPzlb0+Ea/+g==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== JoaoGRRodrigues/rodd/etc/data/rodd-data/xml/tbl_families.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="tbl_families.xsd" generated="2010-06-25T11:54:16">
<tbl_families>
<familyID>1</familyID>
<family>AIDA</family>
<display_name>AIDA</display_name>
</tbl_families>
<tbl_families>
<familyID>2</familyID>
<family>BMD</family>
<display_name>Basic Meteorological Data (BMD)</display_name>
</tbl_families>
<tbl_families>
<familyID>4</familyID>
<family>DAILY_LOGS</family>
</tbl_families>
<tbl_families>
<familyID>5</familyID>
<family>DCP</family>
<display_name>DCP Retransmissions (only for registered DCP operators)</display_name>
</tbl_families>
<tbl_families>
<familyID>6</familyID>
<family>DEVCOCAST_GENERAL</family>
</tbl_families>
<tbl_families>
<familyID>7</familyID>
<family>EARS_ASCAT</family>
<display_name>EARS-ASCAT</display_name>
</tbl_families>
<tbl_families>
<familyID>8</familyID>
<family>EARS_ATOVS</family>
<display_name>EARS-ATOVS</display_name>
</tbl_families>
<tbl_families>
<familyID>9</familyID>
<family>EARS_AVHRR</family>
<display_name>EARS-AVHRR</display_name>
</tbl_families>
<tbl_families>
<familyID>10</familyID>
<family>ERS_SCAT</family>
<display_name>ERS-SCAT</display_name>
</tbl_families>
<tbl_families>
<familyID>11</familyID>
<family>EUM_MET_HIGH_VOL</family>
<display_name>Clear Sky Reflectance Map (high data volume product)</display_name>
</tbl_families>
<tbl_families>
<familyID>12</familyID>
<family>EUM_MET_PRODUCTS</family>
<display_name>Meteosat Meteorological Products</display_name>
</tbl_families>
<tbl_families>
<familyID>13</familyID>
<family>FSD_1_HOUR</family>
<display_name> 1-hourly GOES &amp; MT-SAT image data</display_name>
</tbl_families>
<tbl_families>
<familyID>14</familyID>
<family>FSD_3_HOUR</family>
<display_name> 3-hourly GOES &amp; MT-SAT image data</display_name>
</tbl_families>
<tbl_families>
<familyID>15</familyID>
<family>GNC_CN_CMA</family>
<display_name> China Meteorological Administration (CMA) Products</display_name>
</tbl_families>
<tbl_families>
<familyID>16</familyID>
<family>HR_SEVIRI_QUARTER</family>
<display_name>High Rate SEVIRI Image Data 0º longitude: 1/4-hourly data transmissions **</display_name>
</tbl_families>
<tbl_families>
<familyID>17</familyID>
<family>IODC_HALF</family>
<display_name>High Resolution Image Indian Ocean Data Coverage: 1/2-hourly data transmissions</display_name>
</tbl_families>
<tbl_families>
<familyID>18</familyID>
<family>JASON</family>
<display_name>Jason/OSTM Products</display_name>
</tbl_families>
<tbl_families>
<familyID>19</familyID>
<family>LR_SEVIRI_HALF</family>
<display_name>Low Rate SEVIRI Image Data 0º longitude (near real time data):</display_name>
</tbl_families>
<tbl_families>
<familyID>20</familyID>
<family>LSA_SAF_PRODUCTS</family>
<display_name>Land Surface Analysis Applications (LSA-SAF Products)</display_name>
</tbl_families>
<tbl_families>
<familyID>21</familyID>
<family>MDD_ACMAD</family>
<display_name>Meteorological Data Dissemination</display_name>
</tbl_families>
<tbl_families>
<familyID>22</familyID>
<family>MDD_NOMINAL</family>
<display_name>Meteorological Data Dissemination</display_name>
</tbl_families>
<tbl_families>
<familyID>23</familyID>
<family>METOP_AMSUA</family>
<display_name>Metop AMSU_A</display_name>
</tbl_families>
<tbl_families>
<familyID>24</familyID>
<family>METOP_ASCAT</family>
<display_name>Metop ASCAT</display_name>
</tbl_families>
<tbl_families>
<familyID>25</familyID>
<family>METOP_ASCAT_SOMO</family>
<display_name>EUMETSAT Metop ASCAT Surface Soil Moisture</display_name>
</tbl_families>
<tbl_families>
<familyID>26</familyID>
<family>METOP_AVHRR</family>
<display_name>Metop AVHRR</display_name>
</tbl_families>
<tbl_families>
<familyID>27</familyID>
<family>METOP_GOME</family>
<display_name>Metop GOME</display_name>
</tbl_families>
<tbl_families>
<familyID>28</familyID>
<family>METOP_GRASS</family>
<display_name>Metop GRAS</display_name>
</tbl_families>
<tbl_families>
<familyID>29</familyID>
<family>METOP_HIRS</family>
<display_name>Metop HIRS</display_name>
</tbl_families>
<tbl_families>
<familyID>30</familyID>
<family>METOP_IASI</family>
<display_name>Metop IASI</display_name>
</tbl_families>
<tbl_families>
<familyID>31</familyID>
<family>METOP_MHS</family>
<display_name>Metop MHS</display_name>
</tbl_families>
<tbl_families>
<familyID>32</familyID>
<family>METOP_NOAA_ATOVS_SOUNDING_PRODUCTS</family>
<display_name>Metop/NOAA ATOVS Sounding Products</display_name>
</tbl_families>
<tbl_families>
<familyID>33</familyID>
<family>MODIS_GLOBAL_FIRE_PRODUCTS</family>
<display_name>MODIS Global Fire products</display_name>
</tbl_families>
<tbl_families>
<familyID>34</familyID>
<family>MODIS_POLAR_WINDS</family>
<display_name>MODIS Polar Winds</display_name>
</tbl_families>
<tbl_families>
<familyID>35</familyID>
<family>MSG_RSS</family>
<display_name>Meteosat Rapid Scanning Service (RSS) 9.5 degrees East **</display_name>
</tbl_families>
<tbl_families>
<familyID>36</familyID>
<family>NASA_SERVIR</family>
<display_name>NASA-SERVIR</display_name>
</tbl_families>
<tbl_families>
<familyID>38</familyID>
<family>NOAA_AMSU_A</family>
<display_name>NOAA AMSU_A</display_name>
</tbl_families>
<tbl_families>
<familyID>39</familyID>
<family>NOAA_AVHRR</family>
<display_name>NOAA AVHRR</display_name>
</tbl_families>
<tbl_families>
<familyID>40</familyID>
<family>NOAA_HIRS</family>
<display_name>NOAA HIRS</display_name>
</tbl_families>
<tbl_families>
<familyID>41</familyID>
<family>NOAA_MHS</family>
<display_name>NOAA MHS</display_name>
</tbl_families>
<tbl_families>
<familyID>42</familyID>
<family>NOT_DEFINED</family>
</tbl_families>
<tbl_families>
<familyID>43</familyID>
<family>O3M_SAF</family>
<display_name>Ozone &amp; Atmospheric Chemistry Applications (O3M-SAF Products)</display_name>
</tbl_families>
<tbl_families>
<familyID>44</familyID>
<family>SAF_GRAS</family>
<display_name>GRAS Meteorology (GRAS SAF)</display_name>
</tbl_families>
<tbl_families>
<familyID>45</familyID>
<family>SAF_OSI</family>
<display_name>Ocean &amp; Sea Ice Applications (OSI-SAF Products)</display_name>
</tbl_families>
<tbl_families>
<familyID>46</familyID>
<family>VITO</family>
<display_name>VITO - VEGETATION products (restricted to African NMS and partner organisations)</display_name>
</tbl_families>
<tbl_families>
<familyID>47</familyID>
<family>HR_SEVIRI_HALF</family>
<display_name>High Rate SEVIRI Image Data 0º longitude: 1/2-hourly data transmissions **</display_name>
</tbl_families>
<tbl_families>
<familyID>48</familyID>
<family>HR_SEVIRI_1_HOUR</family>
<display_name>High Rate SEVIRI Image Data 0º longitude: 1-hourly data transmissions **</display_name>
</tbl_families>
<tbl_families>
<familyID>49</familyID>
<family>HR_SEVIRI_3_HOUR</family>
<display_name>High Rate SEVIRI Image Data 0º longitude: 3-hourly data transmissions **</display_name>
</tbl_families>
<tbl_families>
<familyID>50</familyID>
<family>HR_SEVIRI_6_HOUR</family>
<display_name>High Rate SEVIRI Image Data 0º longitude: 6-hourly data transmissions</display_name>
</tbl_families>
<tbl_families>
<familyID>51</familyID>
<family>LR_SEVIRI_1_HOUR</family>
<display_name>Low Rate SEVIRI Image Data 0º longitude (near real time data):</display_name>
</tbl_families>
<tbl_families>
<familyID>53</familyID>
<family>LR_SEVIRI_3_HOUR</family>
<display_name>Low Rate SEVIRI Image Data 0º longitude (near real time data):</display_name>
</tbl_families>
<tbl_families>
<familyID>54</familyID>
<family>LR_SEVIRI_6_HOUR</family>
<display_name>Low Rate SEVIRI Image Data 0º longitude (near real time data):</display_name>
</tbl_families>
<tbl_families>
<familyID>55</familyID>
<family>IODC_1_HOUR</family>
<display_name>High Resolution Image Indian Ocean Data Coverage: 1-hourly data transmission</display_name>
</tbl_families>
<tbl_families>
<familyID>56</familyID>
<family>IODC_3_HOUR</family>
<display_name>High Resolution Image Indian Ocean Data Coverage: 3-hourly data transmission</display_name>
</tbl_families>
<tbl_families>
<familyID>57</familyID>
<family>IODC_6_HOUR</family>
<display_name>High Resolution Image Indian Ocean Data Coverage: 6-hourly data transmission</display_name>
</tbl_families>
<tbl_families>
<familyID>58</familyID>
<family>TRIAL</family>
<display_name>Trial Products</display_name>
</tbl_families>
<tbl_families>
<familyID>59</familyID>
<family>ESSENTIAL</family>
</tbl_families>
<tbl_families>
<familyID>60</familyID>
<family>MODIS_GLOBAL_OCEAN_COLOUR_PROD</family>
<display_name>MODIS Global Ocean Colour products</display_name>
</tbl_families>
<tbl_families>
<familyID>61</familyID>
<family>MODIS_THINNED</family>
<display_name>MODIS thinned level 1 products</display_name>
</tbl_families>
</dataroot>
