=== JoaoGRRodrigues/rodd/etc/data/rodd-data/tbl_service_family_link.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="tbl_service_family_link" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="tbl_service_family_link">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="familyID" index-key="familyID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="serviceID " primary="no" unique="no" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="1"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAD7h+L2mQm1Qpb51SH52ikoAAAAAOdrMzSTqeNAAAAAAAAAAAB0AGIA
bABfAHMAZQByAHYAaQBjAGUAXwBmAGEAbQBpAGwAeQBfAGwAaQBuAGsAAAAAAAAA
qwFO8j0BZk6n/tKlXARaiAAAAADJIMaFtq3jQADo2wlYYRMAdABiAGwAXwBzAGUA
cgB2AGkAYwBlAAAAAAAAAJbVlJ2X0nNCg0vxHwBwRbgHAAAAqwFO8j0BZk6n/tKl
XARaiFMAZQByAHYAaQBjAGUASQBEAAAAAAAAAG3cd7W/bEpOn22XqAomTvEHAAAA
qwFO8j0BZk6n/tKlXARaiHMAZQByAHYAaQBjAGUAXwBkAGkAcgBlAGMAdABvAHIA
eQAAAAAAAACsYaxSGiWJSJwIZy/5CAA6BwAAAPuH4vaZCbVClvnVIfnaKShzAGUA
cgB2AGkAYwBlAEkARAAAAAAAAACaCx/FiT/iTZzfktUvTAtEAAAAALPf2ZFTqeNA
AOjbCVhhEwB0AGIAbABfAGYAYQBtAGkAbABpAGUAcwAAAAAAAACpzw32EhUyR7bL
2l0+J8nrBwAAAJoLH8WJP+JNnN+S1S9MC0RmAGEAbQBpAGwAeQBJAEQAAAAAAAAA
iSZkL9Z4vUqNeP7OudTA1wcAAACaCx/FiT/iTZzfktUvTAtEZgBhAG0AaQBsAHkA
AAAAAAAACVVnKJZo3kKCFicYU17I/AcAAAD7h+L2mQm1Qpb51SH52ikoZgBhAG0A
aQBsAHkASQBEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAABAAAAAAAAAAAAAAA
AAAAAAAA
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="+4fi9pkJtUKW+dUh+dopKA==
"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="OrderBy" type="12" value="[Lookup_familyID].[family], [Lookup_serviceID].[service_directory]"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="serviceID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2595"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="110"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="GUID" type="9" value="rGGsUholiUicCGcv+QgAOg==
"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="1"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="0"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1134"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="0twip"/>
<od:fieldProperty name="LimitToList" type="1" value="0"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT tbl_service.ServiceID, tbl_service.service_directory FROM tbl_service; "/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="familyID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2490"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="110"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="GUID" type="9" value="CVVnKJZo3kKCFicYU17I/A==
"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT tbl_families.familyID, tbl_families.family FROM tbl_families ORDER BY tbl_families.family; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="1"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="0"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1134"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== JoaoGRRodrigues/rodd/etc/data/rodd-data/tbl_service_family_link.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="tbl_service_family_link.xsd" generated="2010-06-25T11:54:45">
<tbl_service_family_link>
<serviceID>41</serviceID>
<familyID>23</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>61</serviceID>
<familyID>38</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>43</serviceID>
<familyID>24</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>33</serviceID>
<familyID>7</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>44</serviceID>
<familyID>25</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>816</serviceID>
<familyID>45</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>45</serviceID>
<familyID>32</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>32</serviceID>
<familyID>8</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>47</serviceID>
<familyID>26</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>63</serviceID>
<familyID>39</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>120</serviceID>
<familyID>12</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>141</serviceID>
<familyID>12</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>143</serviceID>
<familyID>12</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>71</serviceID>
<familyID>15</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>827</serviceID>
<familyID>2</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>828</serviceID>
<familyID>2</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>138</serviceID>
<familyID>11</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>137</serviceID>
<familyID>12</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>142</serviceID>
<familyID>12</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>132</serviceID>
<familyID>5</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>795</serviceID>
<familyID>20</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>804</serviceID>
<familyID>20</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>799</serviceID>
<familyID>20</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>36</serviceID>
<familyID>10</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>17</serviceID>
<familyID>6</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>134</serviceID>
<familyID>14</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>135</serviceID>
<familyID>13</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>49</serviceID>
<familyID>27</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>51</serviceID>
<familyID>28</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>53</serviceID>
<familyID>29</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>56</serviceID>
<familyID>30</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>57</serviceID>
<familyID>30</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>92</serviceID>
<familyID>18</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>93</serviceID>
<familyID>18</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>16</serviceID>
<familyID>6</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>59</serviceID>
<familyID>31</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>67</serviceID>
<familyID>41</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>72</serviceID>
<familyID>1</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>85</serviceID>
<familyID>36</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>107</serviceID>
<familyID>33</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>104</serviceID>
<familyID>22</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>105</serviceID>
<familyID>22</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>100</serviceID>
<familyID>21</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>106</serviceID>
<familyID>22</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>147</serviceID>
<familyID>17</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>149</serviceID>
<familyID>55</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>148</serviceID>
<familyID>56</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>150</serviceID>
<familyID>57</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>147</serviceID>
<familyID>55</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>147</serviceID>
<familyID>56</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>147</serviceID>
<familyID>57</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>149</serviceID>
<familyID>56</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>149</serviceID>
<familyID>57</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>148</serviceID>
<familyID>57</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>123</serviceID>
<familyID>16</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>124</serviceID>
<familyID>16</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>124</serviceID>
<familyID>47</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>126</serviceID>
<familyID>16</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>126</serviceID>
<familyID>47</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>126</serviceID>
<familyID>48</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>125</serviceID>
<familyID>16</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>125</serviceID>
<familyID>47</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>125</serviceID>
<familyID>48</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>125</serviceID>
<familyID>49</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>127</serviceID>
<familyID>16</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>127</serviceID>
<familyID>47</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>127</serviceID>
<familyID>48</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>127</serviceID>
<familyID>49</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>127</serviceID>
<familyID>50</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>128</serviceID>
<familyID>19</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>130</serviceID>
<familyID>19</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>130</serviceID>
<familyID>51</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>129</serviceID>
<familyID>19</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>129</serviceID>
<familyID>51</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>129</serviceID>
<familyID>53</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>131</serviceID>
<familyID>19</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>131</serviceID>
<familyID>51</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>131</serviceID>
<familyID>53</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>131</serviceID>
<familyID>54</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>809</serviceID>
<familyID>43</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>791</serviceID>
<familyID>44</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>825</serviceID>
<familyID>46</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>4</serviceID>
<familyID>33</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>144</serviceID>
<familyID>12</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>146</serviceID>
<familyID>35</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>145</serviceID>
<familyID>12</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>139</serviceID>
<familyID>12</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>136</serviceID>
<familyID>14</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>101</serviceID>
<familyID>21</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>62</serviceID>
<familyID>32</familyID>
</tbl_service_family_link>
<tbl_service_family_link>
<serviceID>822</serviceID>
