=== JoaoGRRodrigues/rodd/etc/data/rodd-data/tbl_service.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="tbl_service" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="tbl_service">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="Field1" index-key="serviceID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="1"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAACrAU7yPQFmTqf+0qVcBFqIAAAAABA532RVreNAAAAAAAAAAAB0AGIA
bABfAHMAZQByAHYAaQBjAGUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAACrAU7y
PQFmTqf+0qVcBFqIYwBoAGEAbgBuAGUAbAAAAAAAAACW1ZSdl9JzQoNL8R8AcEW4
BwAAAKsBTvI9AWZOp/7SpVwEWohzAGUAcgB2AGkAYwBlAEkARAAAAAAAAABt3He1
v2xKTp9tl6gKJk7xBwAAAKsBTvI9AWZOp/7SpVwEWohzAGUAcgB2AGkAYwBlAF8A
ZABpAHIAZQBjAHQAbwByAHkAAAAAAAAAJGmdZVtcQkeu1Y0HZHjUgQAAAABEAJhK
FajjQAAAAAAAAAAAdABiAGwALQBjAGgAYQBuAG4AZQBsAHMAIABRAHUAZQByAHkA
AAAAAAAAUwOyJ3afWk6+HTR3Jzt0HwcAAACrAU7yPQFmTqf+0qVcBFqIYwBoAGEA
bgBuAGUAbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAQAAAAAAAAAAAAAAAAA
AAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="qwFO8j0BZk6n/tKlXARaiA==
"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="DatasheetFontName" type="10" value="Calibri"/>
<od:tableProperty name="DatasheetFontHeight" type="3" value="18"/>
<od:tableProperty name="DatasheetFontWeight" type="3" value="400"/>
<od:tableProperty name="DatasheetFontItalic" type="1" value="0"/>
<od:tableProperty name="DatasheetFontUnderline" type="1" value="0"/>
<od:tableProperty name="TabularCharSet" type="2" value="186"/>
<od:tableProperty name="TabularFamily" type="2" value="34"/>
<od:tableProperty name="DatasheetForeColor" type="4" value="0"/>
<od:tableProperty name="DatasheetForeColor12" type="4" value="0"/>
<od:tableProperty name="OrderBy" type="12" value="[tbl_service].[serviceID], [tbl_service].[service_directory], [Lookup_channel].[channel]"/>
<od:tableProperty name="Filter" type="12" value="([Lookup_channel].[channel]=&quot;EUMETSAT Data Channel 9&quot;)"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="serviceID" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="General Number"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1665"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="GUID" type="9" value="ltWUnZfSc0KDS/EfAHBFuA==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="service_directory" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="ColumnWidth" type="3" value="4725"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="GUID" type="9" value="bdx3tb9sSk6fbZeoCiZO8Q==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="channel" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="11700"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="110"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="tbl-channels Query"/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="1"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;2268"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="GUID" type="9" value="UwOyJ3afWk6+HTR3Jzt0Hw==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== JoaoGRRodrigues/rodd/etc/data/rodd-data/tbl_service.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="tbl_service.xsd" generated="2010-06-25T11:52:37">
<tbl_service>
<serviceID>1</serviceID>
<service_directory>Not_Required</service_directory>
</tbl_service>
<tbl_service>
<serviceID>2</serviceID>
<service_directory>aida-1-test</service_directory>
<channel>25</channel>
</tbl_service>
<tbl_service>
<serviceID>3</serviceID>
<service_directory>channel-12-test-1</service_directory>
<channel>13</channel>
</tbl_service>
<tbl_service>
<serviceID>4</serviceID>
<service_directory>channel-4-test</service_directory>
<channel>5</channel>
</tbl_service>
<tbl_service>
<serviceID>5</serviceID>
<service_directory>channel-4-test-1</service_directory>
<channel>5</channel>
</tbl_service>
<tbl_service>
<serviceID>6</serviceID>
<service_directory>channel-4-test-2</service_directory>
<channel>5</channel>
</tbl_service>
<tbl_service>
<serviceID>7</serviceID>
<service_directory>channel-5-test</service_directory>
<channel>6</channel>
</tbl_service>
<tbl_service>
<serviceID>8</serviceID>
<service_directory>channel-6-test</service_directory>
<channel>7</channel>
</tbl_service>
<tbl_service>
<serviceID>9</serviceID>
<service_directory>channel-7-test</service_directory>
<channel>8</channel>
</tbl_service>
<tbl_service>
<serviceID>10</serviceID>
<service_directory>channel-8-test-1</service_directory>
<channel>9</channel>
</tbl_service>
<tbl_service>
<serviceID>11</serviceID>
<service_directory>channel-8-test-2</service_directory>
<channel>9</channel>
</tbl_service>
<tbl_service>
<serviceID>12</serviceID>
<service_directory>dailylog-trial</service_directory>
<channel>15</channel>
</tbl_service>
<tbl_service>
<serviceID>13</serviceID>
<service_directory>dbwinds-modis</service_directory>
<channel>5</channel>
</tbl_service>
<tbl_service>
<serviceID>14</serviceID>
<service_directory>devcocast-1-test</service_directory>
<channel>23</channel>
</tbl_service>
<tbl_service>
<serviceID>15</serviceID>
<service_directory>devcocast-1-trial</service_directory>
<channel>23</channel>
</tbl_service>
<tbl_service>
<serviceID>16</serviceID>
<service_directory>devcocast-afr</service_directory>
<channel>23</channel>
</tbl_service>
<tbl_service>
<serviceID>17</serviceID>
<service_directory>devcocast-sam</service_directory>
<channel>23</channel>
</tbl_service>
<tbl_service>
<serviceID>18</serviceID>
<service_directory>devcocast-vgt-sam</service_directory>
<channel>23</channel>
</tbl_service>
<tbl_service>
<serviceID>19</serviceID>
<service_directory>DWD-DWDintern</service_directory>
<channel>17</channel>
</tbl_service>
<tbl_service>
<serviceID>20</serviceID>
<service_directory>DWD-ECM</service_directory>
<channel>17</channel>
</tbl_service>
<tbl_service>
<serviceID>21</serviceID>
<service_directory>DWD-EUM</service_directory>
<channel>17</channel>
</tbl_service>
<tbl_service>
<serviceID>22</serviceID>
<service_directory>DWD-GDS</service_directory>
<channel>17</channel>
</tbl_service>
<tbl_service>
<serviceID>23</serviceID>
<service_directory>DWD-GME</service_directory>
<channel>17</channel>
</tbl_service>
<tbl_service>
<serviceID>24</serviceID>
<service_directory>DWD-LM</service_directory>
<channel>17</channel>
</tbl_service>
<tbl_service>
<serviceID>25</serviceID>
<service_directory>DWD-LMK</service_directory>
<channel>17</channel>
</tbl_service>
<tbl_service>
<serviceID>26</serviceID>
<service_directory>DWD-MOS</service_directory>
<channel>17</channel>
</tbl_service>
<tbl_service>
<serviceID>27</serviceID>
<service_directory>DWD-RAD</service_directory>
<channel>17</channel>
</tbl_service>
<tbl_service>
<serviceID>28</serviceID>
<service_directory>DWD-RBSN</service_directory>
<channel>17</channel>
</tbl_service>
<tbl_service>
<serviceID>29</serviceID>
<service_directory>DWD-SYN</service_directory>
<channel>17</channel>
</tbl_service>
<tbl_service>
<serviceID>30</serviceID>
<service_directory>DWD-WAFS</service_directory>
<channel>17</channel>
</tbl_service>
<tbl_service>
<serviceID>31</serviceID>
<service_directory>DWD-WWW</service_directory>
<channel>17</channel>
</tbl_service>
<tbl_service>
<serviceID>32</serviceID>
<service_directory>ears</service_directory>
<channel>2</channel>
</tbl_service>
<tbl_service>
<serviceID>33</serviceID>
<service_directory>ears-ascat</service_directory>
<channel>2</channel>
</tbl_service>
<tbl_service>
<serviceID>34</serviceID>
<service_directory>ears-atovs</service_directory>
<channel>2</channel>
</tbl_service>
<tbl_service>
<serviceID>35</serviceID>
<service_directory>ears-avhrr</service_directory>
<channel>2</channel>
</tbl_service>
<tbl_service>
<serviceID>36</serviceID>
<service_directory>ears-ers-scat</service_directory>
<channel>2</channel>
</tbl_service>
<tbl_service>
<serviceID>37</serviceID>
<service_directory>ears-iasi</service_directory>
<channel>2</channel>
</tbl_service>
<tbl_service>
<serviceID>38</serviceID>
<service_directory>ears-test</service_directory>
<channel>2</channel>
</tbl_service>
<tbl_service>
<serviceID>39</serviceID>
<service_directory>EPS-METOP-ADCS-L0</service_directory>
<channel>27</channel>
</tbl_service>
<tbl_service>
<serviceID>40</serviceID>
<service_directory>EPS-METOP-AMSA-L0</service_directory>
<channel>28</channel>
</tbl_service>
<tbl_service>
<serviceID>41</serviceID>
<service_directory>EPS-METOP-AMSA-L1</service_directory>
<channel>28</channel>
</tbl_service>
<tbl_service>
<serviceID>42</serviceID>
<service_directory>EPS-METOP-ASCA-L0</service_directory>
<channel>29</channel>
</tbl_service>
<tbl_service>
<serviceID>43</serviceID>
<service_directory>EPS-METOP-ASCA-L1</service_directory>
<channel>29</channel>
</tbl_service>
<tbl_service>
<serviceID>44</serviceID>
<service_directory>EPS-METOP-ASCA-L2</service_directory>
<channel>29</channel>
</tbl_service>
<tbl_service>
<serviceID>45</serviceID>
<service_directory>EPS-METOP-ATOV-L2</service_directory>
<channel>46</channel>
</tbl_service>
<tbl_service>
<serviceID>46</serviceID>
<service_directory>EPS-METOP-AVHR-L0</service_directory>
<channel>36</channel>
</tbl_service>
<tbl_service>
<serviceID>47</serviceID>
<service_directory>EPS-METOP-AVHR-L1</service_directory>
<channel>36</channel>
</tbl_service>
<tbl_service>
<serviceID>48</serviceID>
<service_directory>EPS-METOP-GOME-L0</service_directory>
<channel>31</channel>
</tbl_service>
<tbl_service>
<serviceID>49</serviceID>
<service_directory>EPS-METOP-GOME-L1</service_directory>
<channel>31</channel>
</tbl_service>
<tbl_service>
<serviceID>50</serviceID>
<service_directory>EPS-METOP-GRAS-L0</service_directory>
<channel>32</channel>
</tbl_service>
<tbl_service>
<serviceID>51</serviceID>
<service_directory>EPS-METOP-GRAS-L1</service_directory>
<channel>32</channel>
</tbl_service>
<tbl_service>
<serviceID>52</serviceID>
<service_directory>EPS-METOP-HIRS-L0</service_directory>
<channel>33</channel>
</tbl_service>
<tbl_service>
<serviceID>53</serviceID>
<service_directory>EPS-METOP-HIRS-L1</service_directory>
<channel>33</channel>
</tbl_service>
<tbl_service>
<serviceID>54</serviceID>
<service_directory>EPS-METOP-HKTM-L0</service_directory>
<channel>38</channel>
</tbl_service>
<tbl_service>
<serviceID>55</serviceID>
<service_directory>EPS-METOP-IASI-L0</service_directory>
<channel>37</channel>
</tbl_service>
<tbl_service>
<serviceID>56</serviceID>
<service_directory>EPS-METOP-IASI-L1</service_directory>
<channel>37</channel>
</tbl_service>
<tbl_service>
<serviceID>57</serviceID>
<service_directory>EPS-METOP-IASI-L2</service_directory>
<channel>37</channel>
</tbl_service>
<tbl_service>
<serviceID>58</serviceID>
<service_directory>EPS-METOP-MHS-L0</service_directory>
<channel>34</channel>
</tbl_service>
<tbl_service>
<serviceID>59</serviceID>
<service_directory>EPS-METOP-MHS-L1</service_directory>
<channel>34</channel>
</tbl_service>
<tbl_service>
<serviceID>60</serviceID>
<service_directory>EPS-METOP-SEM-L0</service_directory>
<channel>35</channel>
</tbl_service>
<tbl_service>
<serviceID>61</serviceID>
<service_directory>EPS-NOAA-AMSA-L1</service_directory>
<channel>39</channel>
</tbl_service>
<tbl_service>
<serviceID>62</serviceID>
<service_directory>EPS-NOAA-ATOV-L2</service_directory>
<channel>46</channel>
</tbl_service>
<tbl_service>
<serviceID>63</serviceID>
<service_directory>EPS-NOAA-AVHR-L1</service_directory>
<channel>41</channel>
</tbl_service>
<tbl_service>
<serviceID>64</serviceID>
<service_directory>EPS-NOAA-COM</service_directory>
<channel>45</channel>
</tbl_service>
<tbl_service>
<serviceID>65</serviceID>
<service_directory>EPS-NOAA-GAC-L0</service_directory>
<channel>41</channel>
</tbl_service>
<tbl_service>
<serviceID>66</serviceID>
<service_directory>EPS-NOAA-HIRS-L1</service_directory>
<channel>42</channel>
</tbl_service>
<tbl_service>
<serviceID>67</serviceID>
<service_directory>EPS-NOAA-MHS-L1</service_directory>
<channel>43</channel>
</tbl_service>
<tbl_service>
<serviceID>68</serviceID>
<service_directory>EPS-SERVICE</service_directory>
<channel>44</channel>
</tbl_service>
<tbl_service>
<serviceID>69</serviceID>
<service_directory>EPS-TEST</service_directory>
<channel>45</channel>
</tbl_service>
<tbl_service>
<serviceID>70</serviceID>
<service_directory>geonetcast-test</service_directory>
<channel>22</channel>
</tbl_service>
<tbl_service>
<serviceID>71</serviceID>
<service_directory>gnc-cn-cma</service_directory>
<channel>12</channel>
</tbl_service>
<tbl_service>
<serviceID>72</serviceID>
<service_directory>gnc-eum-csir</service_directory>
<channel>25</channel>
</tbl_service>
<tbl_service>
<serviceID>73</serviceID>
